In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [72]:
df = pd.read_csv('Cleaned_Laptop_data.csv')

In [73]:
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,Touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,ASUS,Celeron,Intel,Celeron Dual,Missing,4,DDR4,0,1024,Windows,...,15.6,1,No,No,23990,26990,11,3.8,15279,1947
1,ASUS,VivoBook,Intel,Core i3,10th,8,DDR4,512,0,Windows,...,15.6,1,No,No,37990,50990,25,4.3,990,108
2,ASUS,Vivobook,Intel,Core i3,10th,8,DDR4,0,1024,Windows,...,14.1,1,No,No,32890,46990,30,3.9,28,4
3,HP,Core,Intel,Core i3,11th,8,DDR4,512,0,Windows,...,15.6,1,No,Yes,42990,57330,25,4.4,158,18
4,HP,Core,Intel,Core i5,11th,8,DDR4,512,0,Windows,...,15.6,0,No,No,54990,70171,21,4.2,116,15

Current conversion rate from Indian Rupee to USD is 1.00000 INR = 0.01220

In [74]:
df.dtypes

brand               object
model               object
processor_brand     object
processor_name      object
processor_gnrtn     object
ram_gb              object
ram_type            object
ssd                  int64
hdd                  int64
os                  object
os_bit               int64
graphic_card_gb      int64
weight              object
display_size        object
warranty             int64
Touchscreen         object
msoffice            object
latest_price         int64
old_price            int64
discount             int64
star_rating        float64
ratings              int64
reviews              int64
dtype: object

In [75]:
df['latest_price'] = df['latest_price'] * 0.01220

In [76]:
df['old_price'] = df['old_price'] * 0.01220

In [77]:
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,Touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,ASUS,Celeron,Intel,Celeron Dual,Missing,4,DDR4,0,1024,Windows,...,15.6,1,No,No,292.678,329.2780,11,3.8,15279,1947
1,ASUS,VivoBook,Intel,Core i3,10th,8,DDR4,512,0,Windows,...,15.6,1,No,No,463.478,622.0780,25,4.3,990,108
2,ASUS,Vivobook,Intel,Core i3,10th,8,DDR4,0,1024,Windows,...,14.1,1,No,No,401.258,573.2780,30,3.9,28,4
3,HP,Core,Intel,Core i3,11th,8,DDR4,512,0,Windows,...,15.6,1,No,Yes,524.478,699.4260,25,4.4,158,18
4,HP,Core,Intel,Core i5,11th,8,DDR4,512,0,Windows,...,15.6,0,No,No,670.878,856.0862,21,4.2,116,15

In [78]:
df.columns = df.columns.str.lower()

In [79]:
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,ASUS,Celeron,Intel,Celeron Dual,Missing,4,DDR4,0,1024,Windows,...,15.6,1,No,No,292.678,329.2780,11,3.8,15279,1947
1,ASUS,VivoBook,Intel,Core i3,10th,8,DDR4,512,0,Windows,...,15.6,1,No,No,463.478,622.0780,25,4.3,990,108
2,ASUS,Vivobook,Intel,Core i3,10th,8,DDR4,0,1024,Windows,...,14.1,1,No,No,401.258,573.2780,30,3.9,28,4
3,HP,Core,Intel,Core i3,11th,8,DDR4,512,0,Windows,...,15.6,1,No,Yes,524.478,699.4260,25,4.4,158,18
4,HP,Core,Intel,Core i5,11th,8,DDR4,512,0,Windows,...,15.6,0,No,No,670.878,856.0862,21,4.2,116,15

In [80]:
df['touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [81]:
df['msoffice'].unique()

array(['No', 'Yes'], dtype=object)

In [82]:
df['latest_price'] + df['old_price'] / 2

0       457.3170
1       774.5170
2       687.8970
3       874.1910
4      1098.9211
         ...
891     926.4741
892     828.2092
893     927.3464
894     658.6170
895     756.3817
Length: 896, dtype: float64

In [83]:
df['working_average'] = (df['latest_price'] + df['old_price']) / 2

In [84]:
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews,working_average
0,ASUS,Celeron,Intel,Celeron Dual,Missing,4,DDR4,0,1024,Windows,...,1,No,No,292.678,329.2780,11,3.8,15279,1947,310.9780
1,ASUS,VivoBook,Intel,Core i3,10th,8,DDR4,512,0,Windows,...,1,No,No,463.478,622.0780,25,4.3,990,108,542.7780
2,ASUS,Vivobook,Intel,Core i3,10th,8,DDR4,0,1024,Windows,...,1,No,No,401.258,573.2780,30,3.9,28,4,487.2680
3,HP,Core,Intel,Core i3,11th,8,DDR4,512,0,Windows,...,1,No,Yes,524.478,699.4260,25,4.4,158,18,611.9520
4,HP,Core,Intel,Core i5,11th,8,DDR4,512,0,Windows,...,0,No,No,670.878,856.0862,21,4.2,116,15,763.4821

In [85]:
df = df.replace('Yes', 1)
df = df.replace('No', 0)

In [87]:
(df.dtypes == 'object')

brand               True
model               True
processor_brand     True
processor_name      True
processor_gnrtn     True
ram_gb              True
ram_type            True
ssd                False
hdd                False
os                  True
os_bit             False
graphic_card_gb    False
weight              True
display_size        True
warranty           False
touchscreen        False
msoffice           False
latest_price       False
old_price          False
discount           False
star_rating        False
ratings            False
reviews            False
working_average    False
dtype: bool

In [93]:
pd.DataFrame(df['brand'])

      brand
0      asus
1      asus
2      asus
3        hp
4        hp
..      ...
891    dell
892    dell
893      hp
894    asus
895  lenovo

[896 rows x 1 columns]

In [94]:
df['os'].unique()

array(['Windows', 'Mac', 'Missing'], dtype=object)

In [98]:
tst = df[df['os'] == 'Missing']
tst

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews,working_average
21,acer,aspire,intel,i5,missing,5,ddr5,0,0,Missing,...,0,0,0,622.0780,1097.9878,43,4.4,10966,1185,860.0329
52,acer,aspire,amd,NaN,missing,NaN,NaN,0,0,Missing,...,0,0,0,670.8780,1085.8000,38,4.5,3190,414,878.3390
98,msi,katana,intel,i7,missing,NaN,NaN,0,0,Missing,...,0,0,0,1061.2780,1439.4780,26,4.5,218,27,1250.3780
116,acer,nitro,amd,5,missing,NaN,NaN,0,0,Missing,...,0,0,0,731.8780,1219.9878,40,4.5,1946,240,975.9329
119,msi,pulse,intel,i7,missing,NaN,NaN,0,0,Missing,...,0,0,0,1341.8780,1707.8780,21,4.6,78,16,1524.8780
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,lenovo,ideapad,intel,celeron dual,missing,4,lpddr4,0,0,Missing,...,0,0,0,304.8780,425.6580,28,2.8,70,16,365.2680
882,acer,chromebook,intel,celeron dual,missing,4,ddr4,0,0,Missing,...,0,0,0,292.6780,329.4000,11,3.3,61,4,311.0390
883,lenovo,celeron,intel,celeron dual,missing,4,ddr4,0,1024,Missing,...,0,0,0,365.9878,456.2800,19,3.3,19,1,411.1339
887,hp,15q,intel,core i3,7th,4,ddr4,0,1024,Missing,...,0,0,0,402.0510,0.0000,0,4.2,311,27,201.0255
895,lenovo,v15,intel,core i3,10th,4,ddr4,0,1024,Missing,...,0,0,0,487.9878,536.7878,9,3.1,8,1,512.3878

In [114]:
df.iloc[]

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews,working_average
0,asus,celeron,intel,celeron dual,missing,4,ddr4,0,1024,Windows,...,1,0,0,292.6780,329.2780,11,3.8,15279,1947,310.9780
1,asus,vivobook,intel,core i3,10th,8,ddr4,512,0,Windows,...,1,0,0,463.4780,622.0780,25,4.3,990,108,542.7780
2,asus,vivobook,intel,core i3,10th,8,ddr4,0,1024,Windows,...,1,0,0,401.2580,573.2780,30,3.9,28,4,487.2680
3,hp,core,intel,core i3,11th,8,ddr4,512,0,Windows,...,1,0,1,524.4780,699.4260,25,4.4,158,18,611.9520
4,hp,core,intel,core i5,11th,8,ddr4,512,0,Windows,...,0,0,0,670.8780,856.0862,21,4.2,116,15,763.4821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,dell,core,intel,core i3,10th,8,ddr4,256,1024,Windows,...,0,0,0,565.9580,721.0322,21,2.9,95,5,643.4951
892,dell,core,intel,core i3,10th,8,ddr4,0,1024,Windows,...,0,0,0,492.7580,670.9024,26,3.2,83,15,581.8302
893,hp,pavilion,intel,core i5,8th,8,ddr4,128,0,Windows,...,1,0,0,927.3464,0.0000,0,4.3,129,16,463.6732
894,asus,vivobook,intel,core i3,10th,4,ddr4,0,1024,Windows,...,0,0,0,414.6780,487.8780,15,3.4,31,6,451.2780
895,lenovo,v15,intel,core i3,10th,4,ddr4,0,1024,Windows,...,0,0,0,487.9878,536.7878,9,3.1,8,1,512.3878

In [103]:
tst['brand'].unique()

array(['acer', 'msi', 'lenovo', 'asus', 'hp', 'alienware', 'dell'],
      dtype=object)

In [105]:
# Replacing the 'missing' values in the os column with 'windows' as all of the computer brands that are listed sell computers with windows os'

df['os'] = df['os'].replace('Missing', 'Windows')

In [106]:
df['os'].unique()

array(['Windows', 'Mac'], dtype=object)

In [117]:
# df[df['star_rating'] == 0]

In [49]:
# A lot of missing values; may or may not be helpful in its current state

# df[df['processor_gnrtn'] == 'missing']

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews,working_average
0,asus,celeron,intel,celeron dual,missing,4,ddr4,0,1024,Windows,...,1,0,0,292.6780,329.2780,11,3.8,15279,1947,310.9780
6,hp,15s,amd,ryzen 3,missing,8,ddr4,256,1024,Windows,...,1,0,1,512.3878,589.1868,13,4.3,3524,432,550.7873
11,hp,ryzen,amd,ryzen 3,missing,8,ddr4,256,0,Windows,...,1,0,0,463.4780,561.8710,17,4.3,2214,241,512.6745
12,hp,pavilion,amd,ryzen 5,missing,8,ddr4,512,0,Windows,...,1,0,0,707.4780,856.0984,17,4.5,4740,532,781.7882
15,dell,vostro,amd,ryzen 3,missing,8,ddr4,0,1024,Windows,...,1,0,1,439.0780,617.9422,28,4.1,59,12,528.5101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
882,acer,chromebook,intel,celeron dual,missing,4,ddr4,0,0,Missing,...,0,0,0,292.6780,329.4000,11,3.3,61,4,311.0390
883,lenovo,celeron,intel,celeron dual,missing,4,ddr4,0,1024,Missing,...,0,0,0,365.9878,456.2800,19,3.3,19,1,411.1339
884,lenovo,ryzen,amd,ryzen 3,missing,4,ddr4,0,1024,Windows,...,0,0,0,426.8780,450.4606,5,3.3,38,6,438.6693
888,dell,inspiron,amd,ryzen 3,missing,8,ddr4,0,1024,Windows,...,0,0,0,487.8780,629.2028,22,3.1,18,4,558.5404
890,apple,macbook,apple,m1 processor,missing,8,ddr4,512,0,Mac,...,1,0,0,1280.8780,1352.9800,5,4.7,6725,629,1316.9290

In [56]:
df = df.rename(columns={'reviews':'num_reviews'})

In [ ]:
def get_laptop_data():
    '''
    Basic function to full laptop data from the csv file.
    '''
    df = pd.read_csv('Cleaned_Laptop_data.csv')
    
    return df

In [ ]:
def clean_data():
    '''
    This function will use the above function to get the laptop data, as well as clean the data in a way that makes it easier to work with and make sense.
    '''
    # Function to get the basic df from csv file
    df = get_laptop_data()
    # Converting the prices in the dataset from Indian Rupees to USD
    df['latest_price'] = df['latest_price'] * 0.01220
    df['old_price'] = df['old_price'] * 0.01220
    # Lowercasing the column names to simplify working with
    df.columns = df.columns.str.lower()
    # Creating an average of the 
    df['working_average'] = (df['latest_price'] + df['old_price']) / 2
    # Changing the yes's and no's to numerical values
    df = df.replace('Yes', 1)
    df = df.replace('No', 0)
    # Renaming reviews column to num_reviews
    df = df.rename(columns={'reviews':'num_reviews'})
    # Changing the missing values from the os column to windows
    df['os'] = df['os'].replace('Missing', 'Windows')
    
    return df

In [115]:
df

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews,working_average
0,asus,celeron,intel,celeron dual,missing,4,ddr4,0,1024,Windows,...,1,0,0,292.6780,329.2780,11,3.8,15279,1947,310.9780
1,asus,vivobook,intel,core i3,10th,8,ddr4,512,0,Windows,...,1,0,0,463.4780,622.0780,25,4.3,990,108,542.7780
2,asus,vivobook,intel,core i3,10th,8,ddr4,0,1024,Windows,...,1,0,0,401.2580,573.2780,30,3.9,28,4,487.2680
3,hp,core,intel,core i3,11th,8,ddr4,512,0,Windows,...,1,0,1,524.4780,699.4260,25,4.4,158,18,611.9520
4,hp,core,intel,core i5,11th,8,ddr4,512,0,Windows,...,0,0,0,670.8780,856.0862,21,4.2,116,15,763.4821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,dell,core,intel,core i3,10th,8,ddr4,256,1024,Windows,...,0,0,0,565.9580,721.0322,21,2.9,95,5,643.4951
892,dell,core,intel,core i3,10th,8,ddr4,0,1024,Windows,...,0,0,0,492.7580,670.9024,26,3.2,83,15,581.8302
893,hp,pavilion,intel,core i5,8th,8,ddr4,128,0,Windows,...,1,0,0,927.3464,0.0000,0,4.3,129,16,463.6732
894,asus,vivobook,intel,core i3,10th,4,ddr4,0,1024,Windows,...,0,0,0,414.6780,487.8780,15,3.4,31,6,451.2780
895,lenovo,v15,intel,core i3,10th,4,ddr4,0,1024,Windows,...,0,0,0,487.9878,536.7878,9,3.1,8,1,512.3878

**Goals**: 

- ML Model that will cluster the laptops based off of:

    - price
    - mrp
    - processing power
    - screen size
    - rating / num ratings

- Clusters valuable enough to use in a classification model
    
**Questions to ask**:

- Is price related to ratings? Number of ratings?
- How are price and screen size related?
- Is price related to processor?

**Measures of Success**:

- Finding top features
- A viable model that achieves our goals
- How will we use this? 

**How to Achieve**:

- Clean data
- Explore data:
    - find anomalies
    - statistical tests
    - visualizations
- Determine most important features
    
**Deliverable**: 

- Reproducable githut repository for other users to rank laptops based upon various features.