In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv('Cleaned_Laptop_data.csv')

In [6]:
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,Touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,ASUS,Celeron,Intel,Celeron Dual,Missing,4,DDR4,0,1024,Windows,...,15.6,1,No,No,23990,26990,11,3.8,15279,1947
1,ASUS,VivoBook,Intel,Core i3,10th,8,DDR4,512,0,Windows,...,15.6,1,No,No,37990,50990,25,4.3,990,108
2,ASUS,Vivobook,Intel,Core i3,10th,8,DDR4,0,1024,Windows,...,14.1,1,No,No,32890,46990,30,3.9,28,4
3,HP,Core,Intel,Core i3,11th,8,DDR4,512,0,Windows,...,15.6,1,No,Yes,42990,57330,25,4.4,158,18
4,HP,Core,Intel,Core i5,11th,8,DDR4,512,0,Windows,...,15.6,0,No,No,54990,70171,21,4.2,116,15

Current conversion rate from Indian Rupee to USD is 1.00000 INR = 0.01220

In [7]:
df.dtypes

brand               object
model               object
processor_brand     object
processor_name      object
processor_gnrtn     object
ram_gb              object
ram_type            object
ssd                  int64
hdd                  int64
os                  object
os_bit               int64
graphic_card_gb      int64
weight              object
display_size        object
warranty             int64
Touchscreen         object
msoffice            object
latest_price         int64
old_price            int64
discount             int64
star_rating        float64
ratings              int64
reviews              int64
dtype: object

In [8]:
df['latest_price'] = df['latest_price'] * 0.01220

In [9]:
df['old_price'] = df['old_price'] * 0.01220

In [10]:
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,Touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,ASUS,Celeron,Intel,Celeron Dual,Missing,4,DDR4,0,1024,Windows,...,15.6,1,No,No,292.678,329.2780,11,3.8,15279,1947
1,ASUS,VivoBook,Intel,Core i3,10th,8,DDR4,512,0,Windows,...,15.6,1,No,No,463.478,622.0780,25,4.3,990,108
2,ASUS,Vivobook,Intel,Core i3,10th,8,DDR4,0,1024,Windows,...,14.1,1,No,No,401.258,573.2780,30,3.9,28,4
3,HP,Core,Intel,Core i3,11th,8,DDR4,512,0,Windows,...,15.6,1,No,Yes,524.478,699.4260,25,4.4,158,18
4,HP,Core,Intel,Core i5,11th,8,DDR4,512,0,Windows,...,15.6,0,No,No,670.878,856.0862,21,4.2,116,15

In [19]:
df.columns = df.columns.str.lower()

In [20]:
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,asus,celeron,intel,celeron dual,missing,4,ddr4,0,1024,Windows,...,15.6,1,No,No,292.678,329.2780,11,3.8,15279,1947
1,asus,vivobook,intel,core i3,10th,8,ddr4,512,0,Windows,...,15.6,1,No,No,463.478,622.0780,25,4.3,990,108
2,asus,vivobook,intel,core i3,10th,8,ddr4,0,1024,Windows,...,14.1,1,No,No,401.258,573.2780,30,3.9,28,4
3,hp,core,intel,core i3,11th,8,ddr4,512,0,Windows,...,15.6,1,No,Yes,524.478,699.4260,25,4.4,158,18
4,hp,core,intel,core i5,11th,8,ddr4,512,0,Windows,...,15.6,0,No,No,670.878,856.0862,21,4.2,116,15

In [12]:
ls = df.columns.tolist()

In [13]:
ls

['brand',
 'model',
 'processor_brand',
 'processor_name',
 'processor_gnrtn',
 'ram_gb',
 'ram_type',
 'ssd',
 'hdd',
 'os',
 'os_bit',
 'graphic_card_gb',
 'weight',
 'display_size',
 'warranty',
 'Touchscreen',
 'msoffice',
 'latest_price',
 'old_price',
 'discount',
 'star_rating',
 'ratings',
 'reviews']

In [ ]:
col_to_lower = df.columns.tolist()

for col in col_to_lower:
    
    df[col] = df[col].str.lower()

In [17]:
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,Touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,asus,celeron,intel,celeron dual,missing,4,ddr4,0,1024,Windows,...,15.6,1,No,No,292.678,329.2780,11,3.8,15279,1947
1,asus,vivobook,intel,core i3,10th,8,ddr4,512,0,Windows,...,15.6,1,No,No,463.478,622.0780,25,4.3,990,108
2,asus,vivobook,intel,core i3,10th,8,ddr4,0,1024,Windows,...,14.1,1,No,No,401.258,573.2780,30,3.9,28,4
3,hp,core,intel,core i3,11th,8,ddr4,512,0,Windows,...,15.6,1,No,Yes,524.478,699.4260,25,4.4,158,18
4,hp,core,intel,core i5,11th,8,ddr4,512,0,Windows,...,15.6,0,No,No,670.878,856.0862,21,4.2,116,15

**Goals**: 

- ML Model that will cluster the laptops based off of:

    - price
    - mrp
    - processing power
    - screen size
    - rating / num ratings

- Clusters valuable enough to use in a classification model
    
**Questions to ask**:

- Is price related to ratings? Number of ratings?
- How are price and screen size related?
- Is price related to processor?

**Measures of Success**:

- Finding top features
- A viable model that achieves our goals
- How will we use this? 

**How to Achieve**:

- Clean data
- Explore data:
    - find anomalies
    - statistical tests
    - visualizations
- Determine most important features
    
**Deliverable**: 

- Reproducable githut repository for other users to rank laptops based upon various features.